/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.client.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.ejemplo.client.logic.dto.ClientPageDTO;
import co.edu.uniandes.csw.ejemplo.client.logic.dto.ClientDTO;
import co.edu.uniandes.csw.ejemplo.client.persistence.api.IClientPersistence;
import co.edu.uniandes.csw.ejemplo.client.persistence.entity.ClientEntity;
import co.edu.uniandes.csw.ejemplo.client.persistence.converter.ClientConverter;
import static co.edu.uniandes.csw.ejemplo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ClientPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ClientPersistence.class.getPackage())
				.addPackage(ClientEntity.class.getPackage())
				.addPackage(IClientPersistence.class.getPackage())
                .addPackage(ClientDTO.class.getPackage())
                .addPackage(ClientConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IClientPersistence clientPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ClientEntity").executeUpdate();
	}

	private List<ClientEntity> data=new ArrayList<ClientEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ClientEntity entity=new ClientEntity();
			entity.setPassword(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createClientTest(){
		ClientDTO dto=new ClientDTO();
		dto.setPassword(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		ClientDTO result=clientPersistence.createClient(dto);
		
		Assert.assertNotNull(result);
		
		ClientEntity entity=em.find(ClientEntity.class, result.getId());
		
		Assert.assertEquals(dto.getPassword(), entity.getPassword());
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getClientsTest(){
		List<ClientDTO> list=clientPersistence.getClients();
		Assert.assertEquals(list.size(), data.size());
        for(ClientDTO dto:list){
        	boolean found=false;
            for(ClientEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getClientTest(){
		ClientEntity entity=data.get(0);
		ClientDTO dto=clientPersistence.getClient(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getPassword(), dto.getPassword());
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteClientTest(){
		ClientEntity entity=data.get(0);
		clientPersistence.deleteClient(entity.getId());
        ClientEntity deleted=em.find(ClientEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateClientTest(){
		ClientEntity entity=data.get(0);
		
		ClientDTO dto=new ClientDTO();
		dto.setId(entity.getId());
		dto.setPassword(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		
		clientPersistence.updateClient(dto);
		
		
		ClientEntity resp=em.find(ClientEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getPassword(), resp.getPassword());	
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getClientPaginationTest(){
		//Page 1
		ClientPageDTO dto1=clientPersistence.getClients(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ClientPageDTO dto2=clientPersistence.getClients(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ClientDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ClientEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ClientDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ClientEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}