/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.item.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.ejemplo.item.logic.dto.ItemPageDTO;
import co.edu.uniandes.csw.ejemplo.item.logic.dto.ItemDTO;
import co.edu.uniandes.csw.ejemplo.item.logic.api.IItemLogicService;
import co.edu.uniandes.csw.ejemplo.item.persistence.ItemPersistence;
import co.edu.uniandes.csw.ejemplo.item.persistence.api.IItemPersistence;
import co.edu.uniandes.csw.ejemplo.item.persistence.entity.ItemEntity;
import co.edu.uniandes.csw.ejemplo.item.persistence.converter.ItemConverter;
import static co.edu.uniandes.csw.ejemplo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ItemLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ItemLogicService.class.getPackage())
				.addPackage(IItemLogicService.class.getPackage())
				.addPackage(ItemPersistence.class.getPackage())
				.addPackage(ItemEntity.class.getPackage())
				.addPackage(IItemPersistence.class.getPackage())
                .addPackage(ItemDTO.class.getPackage())
                .addPackage(ItemConverter.class.getPackage())
                .addPackage(ItemEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IItemLogicService itemLogicService;
	
	@Inject
	private IItemPersistence itemPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<ItemDTO> dtos=itemPersistence.getItems();
		for(ItemDTO dto:dtos){
			itemPersistence.deleteItem(dto.getId());
		}
	}

	private List<ItemDTO> data=new ArrayList<ItemDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ItemDTO pdto=new ItemDTO();
			pdto.setCantidad(generateRandom(Integer.class));
			pdto.setName(generateRandom(String.class));
			pdto.setProductoId(generateRandom(Long.class));
			pdto=itemPersistence.createItem(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createItemTest(){
		ItemDTO ldto=new ItemDTO();
		ldto.setCantidad(generateRandom(Integer.class));
		ldto.setName(generateRandom(String.class));
		ldto.setProductoId(generateRandom(Long.class));
		
		
		ItemDTO result=itemLogicService.createItem(ldto);
		
		Assert.assertNotNull(result);
		
		ItemDTO pdto=itemPersistence.getItem(result.getId());
		
		Assert.assertEquals(ldto.getCantidad(), pdto.getCantidad());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getProductoId(), pdto.getProductoId());	
	}
	
	@Test
	public void getItemsTest(){
		List<ItemDTO> list=itemLogicService.getItems();
		Assert.assertEquals(list.size(), data.size());
        for(ItemDTO ldto:list){
        	boolean found=false;
            for(ItemDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getItemTest(){
		ItemDTO pdto=data.get(0);
		ItemDTO ldto=itemLogicService.getItem(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getCantidad(), ldto.getCantidad());
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getProductoId(), ldto.getProductoId());
        
	}
	
	@Test
	public void deleteItemTest(){
		ItemDTO pdto=data.get(0);
		itemLogicService.deleteItem(pdto.getId());
        ItemDTO deleted=itemPersistence.getItem(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateItemTest(){
		ItemDTO pdto=data.get(0);
		
		ItemDTO ldto=new ItemDTO();
		ldto.setId(pdto.getId());
		ldto.setCantidad(generateRandom(Integer.class));
		ldto.setName(generateRandom(String.class));
		ldto.setProductoId(generateRandom(Long.class));
		
		
		itemLogicService.updateItem(ldto);
		
		
		ItemDTO resp=itemPersistence.getItem(pdto.getId());
		
		Assert.assertEquals(ldto.getCantidad(), resp.getCantidad());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getProductoId(), resp.getProductoId());	
	}
	
	@Test
	public void getItemPaginationTest(){
		
		ItemPageDTO dto1=itemLogicService.getItems(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		ItemPageDTO dto2=itemLogicService.getItems(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(ItemDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(ItemDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ItemDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ItemDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        ItemPageDTO dto3=itemLogicService.getItems(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(ItemDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(ItemDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}