/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.carrito.master.logic.ejb;

import co.edu.uniandes.csw.ejemplo.item.logic.dto.ItemDTO;
import co.edu.uniandes.csw.ejemplo.item.persistence.api.IItemPersistence;
import co.edu.uniandes.csw.ejemplo.carrito.logic.dto.CarritoDTO;
import co.edu.uniandes.csw.ejemplo.carrito.master.logic.api._ICarritoMasterLogicService;
import co.edu.uniandes.csw.ejemplo.carrito.master.logic.dto.CarritoMasterDTO;
import co.edu.uniandes.csw.ejemplo.carrito.master.persistence.api.ICarritoMasterPersistence;
import co.edu.uniandes.csw.ejemplo.carrito.master.persistence.entity.CarritoitemEntity;
import co.edu.uniandes.csw.ejemplo.carrito.persistence.api.ICarritoPersistence;
import javax.inject.Inject;

public abstract class _CarritoMasterLogicService implements _ICarritoMasterLogicService {

    @Inject
    protected ICarritoPersistence carritoPersistance;
    @Inject
    protected ICarritoMasterPersistence carritoMasterPersistance;
    @Inject
    protected IItemPersistence itemPersistance;

    public CarritoMasterDTO createMasterCarrito(CarritoMasterDTO carrito) {
        CarritoDTO persistedCarritoDTO = carritoPersistance.createCarrito(carrito.getCarritoEntity());
        if (carrito.getCreateitem() != null) {
            for (ItemDTO itemDTO : carrito.getCreateitem()) {
                ItemDTO createdItemDTO = itemPersistance.createItem(itemDTO);
                CarritoitemEntity carritoItemEntity = new CarritoitemEntity(persistedCarritoDTO.getId(), createdItemDTO.getId());
                carritoMasterPersistance.createCarritoitemEntity(carritoItemEntity);
            }
        }
        // update item
        if (carrito.getUpdateitem() != null) {
            for (ItemDTO itemDTO : carrito.getUpdateitem()) {
                itemPersistance.updateItem(itemDTO);
                CarritoitemEntity carritoItemEntity = new CarritoitemEntity(persistedCarritoDTO.getId(), itemDTO.getId());
                carritoMasterPersistance.createCarritoitemEntity(carritoItemEntity);
            }
        }
        return carrito;
    }

    public CarritoMasterDTO getMasterCarrito(Long id) {
        return carritoMasterPersistance.getCarrito(id);
    }

    public void deleteMasterCarrito(Long id) {
        carritoPersistance.deleteCarrito(id);
    }

    public void updateMasterCarrito(CarritoMasterDTO carrito) {
        carritoPersistance.updateCarrito(carrito.getCarritoEntity());

        //---- FOR RELATIONSHIP
        // persist new item
        if (carrito.getCreateitem() != null) {
            for (ItemDTO itemDTO : carrito.getCreateitem()) {
                ItemDTO createdItemDTO = itemPersistance.createItem(itemDTO);
                CarritoitemEntity carritoItemEntity = new CarritoitemEntity(carrito.getCarritoEntity().getId(), createdItemDTO.getId());
                carritoMasterPersistance.createCarritoitemEntity(carritoItemEntity);
            }
        }
        // update item
        if (carrito.getUpdateitem() != null) {
            for (ItemDTO itemDTO : carrito.getUpdateitem()) {
                itemPersistance.updateItem(itemDTO);
            }
        }
        // delete item
        if (carrito.getDeleteitem() != null) {
            for (ItemDTO itemDTO : carrito.getDeleteitem()) {
                carritoMasterPersistance.deleteCarritoitemEntity(carrito.getCarritoEntity().getId(), itemDTO.getId());
                itemPersistance.deleteItem(itemDTO.getId());
            }
        }
    }
}
