/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.carrito.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.ejemplo.carrito.logic.dto.CarritoDTO;
import co.edu.uniandes.csw.ejemplo.carrito.logic.api.ICarritoLogicService;
import co.edu.uniandes.csw.ejemplo.carrito.master.logic.api._ICarritoMasterLogicService;
import co.edu.uniandes.csw.ejemplo.carrito.master.logic.dto.CarritoMasterDTO;
import co.edu.uniandes.csw.ejemplo.item.logic.api.IItemLogicService;
import co.edu.uniandes.csw.ejemplo.item.logic.dto.ItemDTO;
import javax.inject.Inject;


public abstract class _CarritoMasterMockLogicService implements _ICarritoMasterLogicService {

    protected static ArrayList<CarritoMasterDTO> carritoMasterDtosList = new ArrayList<CarritoMasterDTO>() ;
    @Inject
    protected IItemLogicService itemPersistance;
    @Inject
    protected ICarritoLogicService carritoPersistance;

    public CarritoMasterDTO createMasterCarrito(CarritoMasterDTO carrito) {

        carritoPersistance.createCarrito(carrito.getCarritoEntity());
        for (ItemDTO dto : carrito.getCreateitem()) {
            itemPersistance.createItem(dto);
        }
        carritoMasterDtosList.add(carrito);
        return carrito;
    }

    public CarritoMasterDTO getMasterCarrito(Long id) {
        for (CarritoMasterDTO carritoMasterDTO : carritoMasterDtosList) {
            if (carritoMasterDTO.getCarritoEntity().getId() == id) {
                return carritoMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterCarrito(Long id) {
        for (CarritoMasterDTO carritoMasterDTO : carritoMasterDtosList) {
            if (carritoMasterDTO.getCarritoEntity().getId() == id) {

                for (ItemDTO dto : carritoMasterDTO.getCreateitem()) {
                    itemPersistance.deleteItem(dto.getId());
                }
                carritoPersistance.deleteCarrito(carritoMasterDTO.getId());
                carritoMasterDtosList.remove(carritoMasterDTO);
            }
        }

    }

    public void updateMasterCarrito(CarritoMasterDTO carrito) {

        // update Item
        if (carrito.getUpdateitem() != null) {
            for (ItemDTO dto : carrito.getUpdateitem()) {
                itemPersistance.updateItem(dto);
            }
        }
        // persist new Item
        if (carrito.getCreateitem() != null) {
            for (ItemDTO dto : carrito.getCreateitem()) {
                ItemDTO persistedItemDTO = itemPersistance.createItem(dto);
                dto = persistedItemDTO;
            }
        }
        // delete Item
        if (carrito.getDeleteitem() != null) {
            for (ItemDTO dto : carrito.getDeleteitem()) {

                itemPersistance.deleteItem(dto.getId());
            }
        }
    }
}