/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.carrito.master.persistence;
import co.edu.uniandes.csw.ejemplo.item.logic.dto.ItemDTO;
import co.edu.uniandes.csw.ejemplo.carrito.master.persistence.entity.CarritoitemEntity;
import co.edu.uniandes.csw.ejemplo.item.persistence.converter.ItemConverter;
import co.edu.uniandes.csw.ejemplo.carrito.logic.dto.CarritoDTO;
import co.edu.uniandes.csw.ejemplo.carrito.master.logic.dto.CarritoMasterDTO;
import co.edu.uniandes.csw.ejemplo.carrito.master.persistence.api._ICarritoMasterPersistence;
import co.edu.uniandes.csw.ejemplo.carrito.persistence.api.ICarritoPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _CarritoMasterPersistence implements _ICarritoMasterPersistence {

  	@PersistenceContext(unitName="carritoPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ICarritoPersistence carritoPersistence;  

    public CarritoMasterDTO getCarrito(Long carritoId) {
        CarritoMasterDTO carritoMasterDTO = new CarritoMasterDTO();
        CarritoDTO carrito = carritoPersistence.getCarrito(carritoId);
        carritoMasterDTO.setCarritoEntity(carrito);
        carritoMasterDTO.setListitem(getCarritoitemEntityList(carritoId));
        return carritoMasterDTO;
    }

    public CarritoitemEntity createCarritoitemEntity(CarritoitemEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteCarritoitemEntity(Long carritoId, Long itemId) {
        Query q = entityManager.createNamedQuery("CarritoitemEntity.deleteCarritoitemEntity");
        q.setParameter("carritoId", carritoId);
        q.setParameter("itemId", itemId);
        q.executeUpdate();
    }

    public List<ItemDTO> getCarritoitemEntityList(Long carritoId) {
        ArrayList<ItemDTO> resp = new ArrayList<ItemDTO>();
        Query q = entityManager.createNamedQuery("CarritoitemEntity.getByMasterId");
        q.setParameter("carritoId",carritoId);
        List<CarritoitemEntity> qResult =  q.getResultList();
        for (CarritoitemEntity entity : qResult) { 
            if(entity.getItemIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ItemConverter.entity2PersistenceDTO(entity.getItemIdEntity()));
        }
        return resp;
    }

}
