/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.producto.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.ejemplo.producto.logic.dto.ProductoDTO;
import co.edu.uniandes.csw.ejemplo.producto.logic.dto.ProductoPageDTO;
import co.edu.uniandes.csw.ejemplo.producto.persistence.api._IProductoPersistence;
import co.edu.uniandes.csw.ejemplo.producto.persistence.converter.ProductoConverter;
import co.edu.uniandes.csw.ejemplo.producto.persistence.entity.ProductoEntity;

public abstract class _ProductoPersistence implements _IProductoPersistence {

  	@PersistenceContext(unitName="carritoPU")
 
	protected EntityManager entityManager;
	
	public ProductoDTO createProducto(ProductoDTO producto) {
		ProductoEntity entity=ProductoConverter.persistenceDTO2Entity(producto);
		entityManager.persist(entity);
		return ProductoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ProductoDTO> getProductos() {
		Query q = entityManager.createQuery("select u from ProductoEntity u");
		return ProductoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ProductoPageDTO getProductos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ProductoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ProductoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ProductoPageDTO response = new ProductoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ProductoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ProductoDTO getProducto(Long id) {
		return ProductoConverter.entity2PersistenceDTO(entityManager.find(ProductoEntity.class, id));
	}

	public void deleteProducto(Long id) {
		ProductoEntity entity=entityManager.find(ProductoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateProducto(ProductoDTO detail) {
		ProductoEntity entity=entityManager.merge(ProductoConverter.persistenceDTO2Entity(detail));
		ProductoConverter.entity2PersistenceDTO(entity);
	}

}