/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.client.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.ejemplo.client.logic.dto.ClientPageDTO;
import co.edu.uniandes.csw.ejemplo.client.logic.dto.ClientDTO;
import co.edu.uniandes.csw.ejemplo.client.logic.api.IClientLogicService;
import co.edu.uniandes.csw.ejemplo.client.persistence.ClientPersistence;
import co.edu.uniandes.csw.ejemplo.client.persistence.api.IClientPersistence;
import co.edu.uniandes.csw.ejemplo.client.persistence.entity.ClientEntity;
import co.edu.uniandes.csw.ejemplo.client.persistence.converter.ClientConverter;
import static co.edu.uniandes.csw.ejemplo.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ClientLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ClientLogicService.class.getPackage())
				.addPackage(IClientLogicService.class.getPackage())
				.addPackage(ClientPersistence.class.getPackage())
				.addPackage(ClientEntity.class.getPackage())
				.addPackage(IClientPersistence.class.getPackage())
                .addPackage(ClientDTO.class.getPackage())
                .addPackage(ClientConverter.class.getPackage())
                .addPackage(ClientEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IClientLogicService clientLogicService;
	
	@Inject
	private IClientPersistence clientPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<ClientDTO> dtos=clientPersistence.getClients();
		for(ClientDTO dto:dtos){
			clientPersistence.deleteClient(dto.getId());
		}
	}

	private List<ClientDTO> data=new ArrayList<ClientDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ClientDTO pdto=new ClientDTO();
			pdto.setPassword(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto=clientPersistence.createClient(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createClientTest(){
		ClientDTO ldto=new ClientDTO();
		ldto.setPassword(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		
		
		ClientDTO result=clientLogicService.createClient(ldto);
		
		Assert.assertNotNull(result);
		
		ClientDTO pdto=clientPersistence.getClient(result.getId());
		
		Assert.assertEquals(ldto.getPassword(), pdto.getPassword());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
	}
	
	@Test
	public void getClientsTest(){
		List<ClientDTO> list=clientLogicService.getClients();
		Assert.assertEquals(list.size(), data.size());
        for(ClientDTO ldto:list){
        	boolean found=false;
            for(ClientDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getClientTest(){
		ClientDTO pdto=data.get(0);
		ClientDTO ldto=clientLogicService.getClient(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getPassword(), ldto.getPassword());
		Assert.assertEquals(pdto.getName(), ldto.getName());
        
	}
	
	@Test
	public void deleteClientTest(){
		ClientDTO pdto=data.get(0);
		clientLogicService.deleteClient(pdto.getId());
        ClientDTO deleted=clientPersistence.getClient(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateClientTest(){
		ClientDTO pdto=data.get(0);
		
		ClientDTO ldto=new ClientDTO();
		ldto.setId(pdto.getId());
		ldto.setPassword(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		
		
		clientLogicService.updateClient(ldto);
		
		
		ClientDTO resp=clientPersistence.getClient(pdto.getId());
		
		Assert.assertEquals(ldto.getPassword(), resp.getPassword());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
	}
	
	@Test
	public void getClientPaginationTest(){
		
		ClientPageDTO dto1=clientLogicService.getClients(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		ClientPageDTO dto2=clientLogicService.getClients(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(ClientDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(ClientDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ClientDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ClientDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        ClientPageDTO dto3=clientLogicService.getClients(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(ClientDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(ClientDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}