/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.carrito.master.persistence.entity;

import co.edu.uniandes.csw.ejemplo.item.persistence.entity.ItemEntity;
import co.edu.uniandes.csw.ejemplo.carrito.persistence.entity.CarritoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(CarritoitemEntityId.class)
@NamedQueries({
    @NamedQuery(name = "CarritoitemEntity.getByMasterId", query = "SELECT  u FROM CarritoitemEntity u WHERE u.carritoId=:carritoId"),
    @NamedQuery(name = "CarritoitemEntity.deleteCarritoitemEntity", query = "DELETE FROM CarritoitemEntity u WHERE u.carritoId=:carritoId and  u.itemId=:itemId")
})
public class CarritoitemEntity implements Serializable {

    @Id
    @Column(name = "carritoId")
    private Long carritoId;
    @Id
    @Column(name = "itemId")
    private Long itemId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "carritoId", referencedColumnName = "id")
    @JoinFetch
    private ItemEntity carritoIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "itemId", referencedColumnName = "id")
    @JoinFetch
    private ItemEntity itemIdEntity; 

    public CarritoitemEntity() {
    }

    public CarritoitemEntity(Long carritoId, Long itemId) {
        this.carritoId =carritoId;
        this.itemId = itemId;
    }

    public Long getCarritoId() {
        return carritoId;
    }

    public void setCarritoId(Long carritoId) {
        this.carritoId = carritoId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public ItemEntity getCarritoIdEntity() {
        return carritoIdEntity;
    }

    public void setCarritoIdEntity(ItemEntity carritoIdEntity) {
        this.carritoIdEntity = carritoIdEntity;
    }

    public ItemEntity getItemIdEntity() {
        return itemIdEntity;
    }

    public void setItemIdEntity(ItemEntity itemIdEntity) {
        this.itemIdEntity = itemIdEntity;
    }

}
