/* ========================================================================
   * Copyright 2014 ejemplo
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 ejemplo
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410152247*/

package co.edu.uniandes.csw.ejemplo.carrito.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.ejemplo.carrito.logic.dto.CarritoDTO;
import co.edu.uniandes.csw.ejemplo.carrito.logic.dto.CarritoPageDTO;
import co.edu.uniandes.csw.ejemplo.carrito.persistence.api._ICarritoPersistence;
import co.edu.uniandes.csw.ejemplo.carrito.persistence.converter.CarritoConverter;
import co.edu.uniandes.csw.ejemplo.carrito.persistence.entity.CarritoEntity;

public abstract class _CarritoPersistence implements _ICarritoPersistence {

  	@PersistenceContext(unitName="carritoPU")
 
	protected EntityManager entityManager;
	
	public CarritoDTO createCarrito(CarritoDTO carrito) {
		CarritoEntity entity=CarritoConverter.persistenceDTO2Entity(carrito);
		entityManager.persist(entity);
		return CarritoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<CarritoDTO> getCarritos() {
		Query q = entityManager.createQuery("select u from CarritoEntity u");
		return CarritoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public CarritoPageDTO getCarritos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from CarritoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from CarritoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		CarritoPageDTO response = new CarritoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(CarritoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public CarritoDTO getCarrito(Long id) {
		return CarritoConverter.entity2PersistenceDTO(entityManager.find(CarritoEntity.class, id));
	}

	public void deleteCarrito(Long id) {
		CarritoEntity entity=entityManager.find(CarritoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateCarrito(CarritoDTO detail) {
		CarritoEntity entity=entityManager.merge(CarritoConverter.persistenceDTO2Entity(detail));
		CarritoConverter.entity2PersistenceDTO(entity);
	}

}